# Generated by Django 6.1.1 on 2026-09-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_veg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='picture',
            field=models.URLField(default='', max_length=500),
        ),
    ]
